### ISSUE TITLE
Parametrics seem to limit overall size to 200x200mm

### ISSUE THREAD

**Issue by InfiniteNesLives** [UnexpectedMaker/vacuum-stencil-box#1]
Amazing project!  Thanks so much for sharing this and the detailed videos!

I'm a fusion360 noob, watched through your video on modifying the parametrics.  My panels are quite large, so I figured I would just print the max size of my prusa MK2S.  So I set the length and width to 210 x 250mm.  When I exported it wasn't filling the build plate as I expected.  I went back and checked the parameters, but it seems it never grows larger than something like 200x200mm.  

Am I doing something wrong?  Or is this a limitation of the design?  Any tips or help is greatly appreciated! :)

![image](https://user-images.githubusercontent.com/28371160/157167967-304d311c-e154-46c4-b871-abd56e317141.png)

**Comment by UnexpectedMaker** [comment]
It's currently forced clamped to 200x200 max size to prevent people from doing silly things.
You can increase that by changing these 2 settings...   (the values I've changed to 300mm
<img width="1206" alt="Screen Shot 2022-03-08 at 3 56 52 pm" src="https://user-images.githubusercontent.com/3156212/157169051-a08c0116-17cc-42c4-9476-b6653f4c3638.png">

Be aware that is unlikely you'll be able to print to the width/length of your bed without getting warping, even with a brim.

**Comment by InfiniteNesLives** [comment]
Thanks for the quick assist.  Able to print the the max now! :)

![image](https://user-images.githubusercontent.com/28371160/157178871-1267b44a-f739-48ff-8253-3ba6b2b86985.png)

**Comment by InfiniteNesLives** [comment]
Everything turned out great!  Just gotta assemble everything now.  My MK2S did pretty well, did have some minor warping of the corners on the main frame.  Went ahead and increased the bed temp from 60C to 70C for the lid and she didn't warp at all.  😁

![image](https://user-images.githubusercontent.com/28371160/157459142-c92bb28e-3248-4a1b-ac0e-e407000f0f62.jpeg)

![image](https://user-images.githubusercontent.com/28371160/157459066-7c702098-627c-4117-84f6-24ea5a8f9c22.jpeg)

![image](https://user-images.githubusercontent.com/28371160/157459110-31b7acad-50bf-45d8-97e3-f9905cbe8dfd.jpeg)

**Comment by UnexpectedMaker** [comment]
Nicely done!!!
